─── error in tupleExpandNamedArgs.chpl:3 [TupleExpansionNamedArgs] ───
  Tuple expansion cannot be used with named arguments.
  A tuple is being expanded here:
      |
    3 | f(a=(...t));
      |     ⎺⎺⎺⎺⎺⎺
      |

─── error in tupleExpandNamedArgs.chpl:3 ───
  Cannot resolve call: no matching candidates

